version: '2'
services:
  server:
    build:
      context: ./server/
    command: npx nodemon src/index.js
    volumes:
      - ./server/:/usr/app
      - /usr/app/node_modules
    ports:
      - "8080:3000"
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
      - SINGLE_BUILD=true
  client:
    build:
      context: ./exercise/
    command: npm start
    volumes:
      - ./exercise/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    environment:
      - REACT_APP_API_HOST=http://localhost:8080
    ports:
      - "3000:3000"
